'use client';

import Head from "next/head";
import React, { useState } from 'react';
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [message, setMessage] = useState('');
  const [response, setResponse] = useState('');

  const handleEncrypt = async () => {
    try {
      const res = await fetch('http://localhost:5050/encrypt', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message }),
      });

      if (!res.ok) {
        throw new Error('Failed to encrypt message');
      }

      const data = await res.json();
      setResponse(data.cyphertext);
    } catch (error) {
      console.error('Error encrypting message:', error);
      setResponse('Failed to encrypt message');
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/honeywell_logo.png"
            alt="Honeywell Logo logo"
            width={180}
            height={90}
            priority
          />

          <h3 className="text-2xl font-bold mb-4">Message Encryption</h3>

          <input
            type="text"
            placeholder="Enter your message"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            className="border p-2 w-full mb-4 rounded"
          />
          <button
            onClick={handleEncrypt}
            className="bg-blue-500 text-white p-2 rounded"
          >
            Encrypt Message
          </button>
          {response && <p className="mt-4">Cyphertext: {response}</p>}
        </main>
      </div>
    </>
  );
}
